# Generated by Django 4.0.4 on 2022-06-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskTitle', models.CharField(max_length=120)),
                ('teskDesc', models.TextField()),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
